# just defaults
language: python
python: 3.7
os: linux

jobs:
  include:
    - name: "Python 3.8 with newest packages on Linux"
      os: linux
      language: python
      python: "3.8"
      before_install:
        - sudo `which pip` install --upgrade pip
      before_script:
        - pip install -U $(cat requirements.txt | awk -F '==|>=' {'print $1'})
        # https://github.com/pypa/virtualenv/pull/1064/files
        - sed -i 's/"rU"/"r"/g' /home/travis/virtualenv/python3.8.0/lib/python3.8/site.py
        - cat /home/travis/virtualenv/python3.8.0/lib/python3.8/site.py
    - name: "Python 3.7 on Linux numba::parallel=False"
      before_script:
        - sed -i s/parallel=True/parallel=False/g PySDM/backends/numba/conf.py
        - sed -i 's/"rU"/"r"/g' /home/travis/virtualenv/python3.7.1/lib/python3.7/site.py
      after_success:
        - codecov
    - name: "Python 3.7 on Linux numba::parallel=True"
      before_script:
        - sed -i s/parallel=False/parallel=True/g PySDM/backends/numba/conf.py
        - sed -i 's/"rU"/"r"/g' /home/travis/virtualenv/python3.7.1/lib/python3.7/site.py
    - name: "Python 3.7 on OSX"
      language: shell
      os: osx
      before_install:
        - export PY_SFX=3
    - name: "Python 3.7 on Windows"
      language: shell
      os: windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip$PY_SFX install -U ipykernel pytest pytest-cov codecov nbconvert jupyter_client setuptools>=50.3.2
  - |
      # https://stackoverflow.com/questions/55486248/deprecationwarning-in-python-3-6-and-3-7-with-pillow-distutils-imp
      if [[ $TRAVIS_OS_NAME == linux ]]; then
        python$PY_SFX $PY_FLAGS -c 'import os, virtualenv; virtualenv.install_distutils(os.environ["VIRTUAL_ENV"])' || exit 1
      fi;
  - pip$PY_SFX install -U -r requirements.txt

script:
  - export PY_FLAGS="-We"
  - NBCONVERT="python$PY_SFX $PY_FLAGS -m nbconvert --to markdown --stdout"
  - PYTEST="python$PY_SFX -m pytest $PY_FLAGS"
  - NUMBA_DISABLE_JIT=1 $PYTEST PySDM_tests/unit_tests --cov-report term --cov=PySDM
  - $PYTEST
  - |
      python$PY_SFX -m ipykernel install --user  # TODO: https://github.com/ipython/ipykernel/issues/560
      for i in PySDM_examples/*/demo.ipynb; do
         $NBCONVERT $i > $i.md.repo;
         $NBCONVERT --execute --ExecutePreprocessor.timeout=1800 $i || exit 1;
      done;
      for i in PySDM_tutorials/*/*.ipynb; do
         $NBCONVERT $i > $i.md.repo;
         $NBCONVERT --execute $i > $i.md.travis || exit 1;
         diff --ignore-all-space $i.md.repo $i.md.travis
      done;
  - |
      if [[ $TRAVIS_OS_NAME == linux ]]; then
        for i in PySDM_examples/*/example*.py; do
          echo $i
          PYTHONPATH=. travis_wait 15 python$PY_SFX $PY_FLAGS $i || exit 1
        done;
      fi;
  # execute Python lines from README.md
  - awk < README.md 'BEGIN {cmt=1; swp=0;} {swp=(substr($0,1,3)=="```"); if (swp && !cmt) {cmt=1; swp=0} if (cmt) print("#" $0); else print $0; if (swp && cmt) {cmt=0; swp=0}}' | python$PY_SFX $PY_FLAGS
