# just defaults
language: python
python: 3.7
os: linux

jobs:
  include:
    - name: "Python 3.8 with newest packages on Linux"
      os: linux
      language: python
      python: "3.8"
      before_install:
        - sudo `which pip` install --upgrade pip
      before_script:
        - pip install -U $(cat requirements.txt | awk -F '==|>=' {'print $1'})
    - name: "Python 3.7 on Linux numba::parallel=False"
      before_script:
        - sed -i s/parallel=True/parallel=False/g PySDM/backends/numba/conf.py
      after_success:
        - codecov
    - name: "Python 3.7 on Linux numba::parallel=True"
      before_script:
        - sed -i s/parallel=False/parallel=True/g PySDM/backends/numba/conf.py
    - name: "Python 3.7 on OSX"
      language: shell
      os: osx
      before_install:
        - sed -i -e '/^ThrustRTC/d' requirements.txt  # TODO
        - sed -i -e '/^CURandRTC/d' requirements.txt  # TODO
        - export PY_SFX=3
    - name: "Python 3.7 on Windows"
      language: shell
      os: windows
      before_install:
        - choco install python --version 3.7
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip$PY_SFX install -U ipykernel pytest pytest-cov codecov nbconvert jupyter_client
  - pip$PY_SFX install -U -r requirements.txt

script:
  - python$PY_SFX -m pytest --ignore submodules --cov-report term --cov=PySDM
  - |
      python$PY_SFX -m ipykernel install --user
      for i in PySDM_examples/*/demo.ipynb; do
         jupyter nbconvert --to markdown --stdout $i > $i.md.repo;
         jupyter nbconvert --ExecutePreprocessor.timeout=1800 --to markdown --execute --stdout $i > $i.md.travis || exit 1;
         # diff $i.md.repo $i.md.travis  # does not make sense with ipywidgets
      done;
  - |
      if [[ $TRAVIS_OS_NAME == linux ]]; then
        for i in PySDM_examples/*/example*.py; do
          echo $i
          PYTHONPATH=. travis_wait 15 python$PY_SFX $i
        done;
      fi;
